feat(plex): try new dockerfile

diff --git a/apps/plex/Dockerfile b/apps/plex/Dockerfile
--- a/apps/plex/Dockerfile
+++ b/apps/plex/Dockerfile
@@ -1,66 +1,80 @@
 FROM docker.io/library/ubuntu:24.04
 
 ARG TARGETPLATFORM
+ARG BUILDPLATFORM
 ARG VERSION
 ARG CHANNEL
 
-ENV DEBCONF_NONINTERACTIVE_SEEN="true" \
-    DEBIAN_FRONTEND="noninteractive" \
-    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE="DontWarn"
-
-ENV UMASK="0002" \
-    TZ="Etc/UTC"
-
 ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility" \
+    PLEX_DOWNLOAD="https://downloads.plex.tv/plex-media-server-new" \
     PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="/config/Library/Application Support" \
     PLEX_MEDIA_SERVER_HOME="/usr/lib/plexmediaserver" \
     PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS="6" \
+    PLEX_MEDIA_SERVER_USER="kah" \
     PLEX_MEDIA_SERVER_INFO_VENDOR="Docker" \
-    PLEX_MEDIA_SERVER_INFO_DEVICE="Docker Container (kodeythomas/containers)"
+    PLEX_MEDIA_SERVER_INFO_DEVICE="Docker Container (geek-cookbook)"
 
-USER root
-WORKDIR /app
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 # hadolint ignore=DL3008,DL3015,SC2039,SC2086
 RUN \
-    apt-get update \
+    apt-get -qq update \
     && \
-    apt-get install -y --no-install-recommends --no-install-suggests \
-        bash \
-        ca-certificates \
-        catatonit \
-        coreutils \
-        curl \
-        jo \
-        jq \
-        nano \
-        tzdata \
-        uuid-runtime \
-        xmlstarlet \
+    apt-get -qq install -y \
+        gnupg2 \
     && \
     case "${TARGETPLATFORM}" in \
         'linux/amd64') \
+            curl -sL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add - \
+            && echo 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' > /etc/apt/sources.list.d/intel.list \
+            && \
             export ARCH='amd64'; \
+            export EXTRA_INSTALL_ARG='intel-opencl-icd=21.49.21786+i643~u20.04'; \
         ;; \
         'linux/arm64') \
             export ARCH='arm64'; \
+            export EXTRA_INSTALL_ARG=''; \
         ;; \
     esac \
     && \
-    curl -fsSL -o /tmp/plex.deb \
-        "https://downloads.plex.tv/plex-media-server-new/${VERSION}/debian/plexmediaserver_${VERSION}_${ARCH}.deb" \
+    apt-get -qq update \
+    && \
+    apt-get -qq install -y \
+        aria2 \
+        uuid-runtime \
+        xmlstarlet \
+        ca-certificates \
+        pulseaudio \
+        ${EXTRA_INSTALL_ARG} \
+    && \
+    echo "Using curl or wget to download the plex debian package result in a qemu failure, why? I dunno" \
+    && \
+    aria2c -d /tmp -o plex.deb \
+        "${PLEX_DOWNLOAD}/${VERSION}/debian/plexmediaserver_${VERSION}_${ARCH}.deb" \
     && \
     dpkg -i --force-confold /tmp/plex.deb \
-    && chmod -R 755 "${PLEX_MEDIA_SERVER_HOME}" \
+    && \
+    apt-get remove -y aria2 gnupg2 \
     && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
     && apt-get autoremove -y \
     && apt-get clean \
-    && rm -rf /etc/default/plexmediaserver /tmp/* /var/lib/apt/lists/* /var/tmp/
+    && \
+    rm -rf \
+        /etc/default/plexmediaserver \
+        /tmp/* \
+        /var/lib/apt/lists/* \
+        /var/tmp/ \
+    && chown -R root:root /app \
+    && chmod -R 755 "${PLEX_MEDIA_SERVER_HOME}" \
+    && printf "umask %d" "${UMASK}" >> /etc/bash.bashrc
 
+WORKDIR "${PLEX_MEDIA_SERVER_HOME}"
+
+ADD https://raw.githubusercontent.com/ChuckPa/PlexDBRepair/master/DBRepair.sh /usr/local/bin/
+RUN sed -i "s/RootRequired=1/RootRequired=0/g" /usr/local/bin/DBRepair.sh && \
+    chmod 755 /usr/local/bin/DBRepair.sh
+
+USER 568
+COPY ./apps/plex/plex-preferences.sh /scripts/plex-preferences.sh
 COPY ./apps/plex/entrypoint.sh /entrypoint.sh
-
-USER nobody:nogroup
-WORKDIR /config
-VOLUME ["/config"]
-
-ENTRYPOINT ["/usr/bin/catatonit", "--", "/entrypoint.sh"]
+CMD ["/entrypoint.sh"]
